# -*- coding: utf-8; mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "7.1" do |web|
    config.vm.box = "bento/centos-7.1"
  end

  config.vm.define "7.2" do |web|
    config.vm.box = "bento/centos-7.2"
  end
end
